### PR TITLE
Feature multifield flagging

### PR DESCRIPTION
**Pull request by jmoldon**
Aim of the branch: making possible to run aoflagger with specific strategies on each source, also when using aoflagger 2.7 (for which field selection does not work).

The best solution I found is to produce individual mms for each field, and then concatenate them with virtualconcat. That way the MMS directory SUBMSS has the following structure:

```
> ls  TEST1.mms/SUBMSS/
TEST1_1331+305.mms.0000.ms/  TEST1_1407+284.mms.0000.ms/  TEST1_1522+3144.mms.0000.ms/  TEST1_1531+3533.mms.0000.ms/
TEST1_1331+305.mms.0001.ms/  TEST1_1407+284.mms.0001.ms/  TEST1_1522+3144.mms.0001.ms/  TEST1_1531+3533.mms.0001.ms/
TEST1_1331+305.mms.0002.ms/  TEST1_1407+284.mms.0002.ms/  TEST1_1522+3144.mms.0002.ms/  TEST1_1531+3533.mms.0002.ms/
TEST1_1331+305.mms.0003.ms/  TEST1_1407+284.mms.0003.ms/  TEST1_1522+3144.mms.0003.ms/  TEST1_1531+3533.mms.0003.ms/
TEST1_1331+305.mms.0004.ms/  TEST1_1407+284.mms.0004.ms/  TEST1_1522+3144.mms.0004.ms/  TEST1_1531+3533.mms.0004.ms/
TEST1_1331+305.mms.0005.ms/  TEST1_1407+284.mms.0005.ms/  TEST1_1522+3144.mms.0005.ms/  TEST1_1531+3533.mms.0005.ms/
TEST1_1331+305.mms.0006.ms/  TEST1_1407+284.mms.0006.ms/  TEST1_1522+3144.mms.0006.ms/  TEST1_1531+3533.mms.0006.ms/
TEST1_1331+305.mms.0007.ms/  TEST1_1407+284.mms.0007.ms/  TEST1_1522+3144.mms.0007.ms/  TEST1_1531+3533.mms.0007.ms/
TEST1_1331+305.mms.0008.ms/  TEST1_1407+284.mms.0008.ms/  TEST1_1522+3144.mms.0008.ms/  TEST1_1531+3533.mms.0008.ms/
```
and aoflagger can be executed on those subdirectories directly. That also has the huge advantage that aoflagger will deal with smaller data sets, and it is much easier to have enough memory to work in -memory-read mode! This solution will also help for further aoflagger runs. It will be useful to flag any source once the bandpass calibration is done, for example. 

Unfortunately, I don't have a good way to do the same with an MS file, it only works with MMS. Probably it is possible to do a virtualconcat on splitted MS files, but it didn't work in the test I did. More tests are needed.

Also, hanning smoothing could be done after the MMS is produced. However, since HS produces a new data set, it changes the field names in the SUBMSS structure, so we lose the field information needed to autoflag by field. So, although it is slower, I do the HS on the MS before converting to MMS.

The new function ms2mms_fields does not work when called from eMERLIN_CASA_functions.py, so I have copied it to eMERLIN_CASA_pipeline.py. This is temporary until we solve the issue #22 .

I have tried this branch with a 21 GB data set and everything seems to work fine. Please check it for any problems. I will also put a link to that data set in the wiki because it is very useful for testing.

Cheers

### CODE REVIEW

**Comment by jradcliffe5** [comment]
Awesome, thanks Javier. That will be really useful! I will try to test it this afternoon. 

Do we have some code which checks the version of aoflagger and uses the function accordingly?

**Comment by jradcliffe5** [comment]
Looking at the code, I think we also need to check which flagging version is faster in terms of mms method too. As far as I know, the mms partition will split the data according to the computer architecture if everything is left to default. From the casa website:

`The user may force the number of “Sub-MSs” in the output MMS by setting the sub-parameter numsubms. The default ’auto’ is to create as many “Sub-MSs” as the number of engines used when starting CASA, in an optimized way.`

I think we need to keep both functions of ms2mms and autoflagger and the check the version of aoflagger. i.e. 2.8 and before, use the functions you wrote and 2.9+ use the original.

**Comment by jmoldon** [comment]
Now checks AOflagger version, and runs two different versions of ms2mms/ms2mms_fields and run_aoflagger/run_aoflagger_fields. Those four tasks are separated for the moment. I have not modified your original ms2mms and run_aoflagger, so they should work with AOflagger 2.9, but please check (any problem should be the same in the master branch).

I have found the solution to some tasks not being recognized when they are in functions.py! We just need to use:
```
from tasks import *
from casa import *
```
The rest also seems to work fine. We should merge this branch before changing too many things related to modules/submodules.

**Comment by jradcliffe5** [comment]
Great glad there was a simple solution to the missing tasks.  Will fork this branch and test later on this afternoon. Nice work Javier!

**Comment by jradcliffe5** [comment]
Didn't have time, will test this now!

**Comment by jradcliffe5** [comment]
Ok the Aoflagger2.9 doesn't work because the ms2mms is done before flagging. I will generate a safeguard using the aoflagging version check that reverses the order if it finds that aoflagger 2.9 is present. Will commit to this branch and then merge.

**Comment by jmoldon** [comment]
That is strange, I thought it was going to be transparent to mms. In my early tests I was running aoflagger 2.7 on mms and all sources were flagged correctly. What is the problem you see? Not flagging/crashing, or not being able to select the correct field?

Trying to do all the flagging before converting to mms is not the best solution, because we will need to refine the flagging later after bandpass.

Alternatively, you can try the ms2mms_fields + run_aoflagger_fields also for 2.9. I don't see why it should be significantly slower, and that would help keeping a common data path.

**Comment by jradcliffe5** [comment]
So the problem comes from rfigui. Even if I go into the subms the gui will crash. Aoflagger runs ok on the mms. 

I think it would be good to allow the user to make their own strategies at the start to take into account source strength etc. 

Separating into fields may not utilise the full number of cores on the machine, we want to make sure it is as fast as possible (I added a issue to test this). 

We can use a general strategy on the mms for later flagging assuming that the majority of rfi has already been excised. This saves having to remake a ms

**Comment by jradcliffe5** [comment]
I also have modified your check_aoflagger_version() so that it only outputs True or False. It keeps the pipeline execution file much smaller. I will commit and you can have a look

**Comment by jradcliffe5** [comment]
Just pushed. Have a look and let me know.

**Comment by jmoldon** [comment]
OK with the rfigui problem, and yes it should be an option available for the user.

But also I think having the rfigui within the pipeline is not a priority now for two reasons. First, there are three default strategies now, two for bright sources and 1 for fainter ones, and they work relatively well. Second, if someone wants to explore the data in detail and find special strategies, they are not going to run the pipeline in one go because that can be time consuming. After hanning smoothing, they will have to stop to search for strategies, so the rfigui step can be done on the MS at that stage as an option. Once that is done, they can continue the normal process ms2mms, flagging, etc. So I suggest adding a new step:
```
importfitsidi
hanning_smoothing
rfigui (with an output list of new strategies to be used later)
ms2mms
run_aoflagger
diagnostics
...
```
My point is, they can use rfigui in the MS, and that is a large enough step to be separated from run_aoflagger anyways.

Maybe that will make it more modular and work for the moment, because run_aoflagger will be very common, but rfigui not so much.

**Comment by jradcliffe5** [comment]
Sure ok, sounds sensible. I have no time today to implement this. Do you have time to put it in soon?

**Comment by jmoldon** [comment]
Yes, no problem. I will make the changes now.

**Comment by jradcliffe5** [comment]
Fab, thanks Javier. Feel free to merge when you've done. Ill then add the calibrator models to the master branch.

**Comment by jradcliffe5** [comment]
wrt to logger, did you keep the write history lines for the ms? The GUI needs those lines to check for any preprocessing information on this source.

**Comment by jmoldon** [comment]
Good news, a lot of new things added:

- Reorganized files in different directories (functions, strategies). Only main pipeline script is kept in the home directory.
- Now the script works from any directory. You don't need to have anything in it. Just call with `-c <where the pipeline is>` and `-i <where the inputs file is>`
- It again needs to modify the sys.path, but does it automatically. This is because CASA funny behaviour with submodules. Anyways the behaviour is very transparent.
- I have updated the README file explaining how to run the pipeline.
- AOFlagger searches for possible strategies following this:
   -  First, check if user has a new strategy for this field in the local folder.
   - If not, check if user has produced a new strategy for this field in the pipeline folder (for typical sources, etc).
   - If not, check for default strategies for this field
   - If nothing is found, just use the default strategy
We can keep default strategies in /aoflagger_strategies/default/<field>.rfis If the user wants to include new strategies (higher priority) they can put them in  /aoflagger_strategies/user/<field>.rfis. That can be done in the current directory or where the pipeline is.
- run_rfigui is now an independent step, and it is run before converting to MMS to avoid problems. Jack, can you update the run_rfigui function so the output goes to the correct user folder (see above)?.
- Global logger added! Using `logging`. It outputs times and message. All messages are printed in the terminal and stored in a file (eMCP.log). Please, add comments to all tasks and important events. `logger.info` is the default, you can put as many `logger.debug` as you want, and it also accepts warning, critical, etc.

I will merge now this version because it is getting huge. Everything I have tested works. Things to be checked in detail: rfigui, all the path through aoflagger 2.9 (ms2mms, run_aoflagger). The GUI opens and seems to work well, but I have not used to process. If there are some bugs we can fix them in the master branch.

NOTE to Jack comment. I have not changed what the GUI reads. Sorry, I still don't understand how the GUI works. I suppose you want to keep minimal information inside the MS (just what tasks have been executed), while keeping more details in the log. Is that right?

**Comment by jradcliffe5** [comment]
Fantastic, great work Javier. I will test it when I have time but may be the weekend now. 

I guess we should chat at some point regarding next steps and what we should work on each?

Wrt to gui stuff, yeah you are right. We want to have both logging and the ms.writehistory part for each task that is run. More detail in logger and basically a line in the ms history. The GUI has a button which checks the history already. In the future, we could use the ms history to generate suggested input file parameters, and/or GUI entries automatically, based upon what pre-processing has already been done. It would make it much easier to then restart the pipeline, if you only want to do a few steps at a time.

**Comment by jmoldon** [comment]
Sure. I wanted to have this first structural part clear and ready to be able to start with the calibration, the real part! Now with the structure it will be easier to contribute to things in parallel. I think now we need this:

- A checklist of main calibration steps. Than then we can convert to issues and start implementing. Probably the checklist itself can be in an issue (pinning first comment or something like that?).
- A time line of which steps do we want for each version, to have a clear idea of the milestones.
- We should put a kind of changelog for those milestones in the wiki.

Probably we can have all those in the wiki, and then update the issues accordingly. We can also have a skype chat or something to put things in common quickly.

For the GUI, yes, all the ms.writehistory are still there, so no problem. That is really useful because the logs can come and go, but the history stays in the file.

**Comment by jradcliffe5** [comment]
Sure sounds good. I think this is the time to get everyone involved so that all the experts can contribute tasks/functions etc. Shall we set up a telecon for sometime next week? I can send out a doodle poll.
We may also want to spend some of the meeting explaining about collaborative github too. I think it can be a bit daunting at the beginning.

We should also add an ‘example function’, including, for example, the syntax of the logger & ms.writehistory, so that others contributing to the pipeline can use this to keep the coding consistent & hopefully reduce bugs.

Wrt the checklist, we can put it the wiki and then reference each step to an individual issue. It means that each calibration step has its own comment log for it, so issues can be flagged more directly & we can assign tasks to contributors.

**Pull request merged**
